
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from cmath import pi
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
import tkinter.messagebox as mgbox
from pyrsistent import b
import pymysql
from kawayiQuasimodo import yonghujiemian
from CQUPTEMS_QT.TKINTER.sign_in import denglu

def run_sign_up_page():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path("./assets")


    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)


    window = Tk()

    window.geometry("1024x634")
    window.configure(bg = "#8a9eff")


    
    # global user_name,user_student_ID,user_phone_number,user_password
    user_name=StringVar()
    user_student_ID=StringVar()
    user_phone_number=StringVar()
    user_password=StringVar()
    
    def generate_unique_pickup_code(name: str,student_id:str)->str:
        """输入两个字符串:姓名和学号,根据这两个字符串生成一个唯一的取件码

        Args:
            name (str): 姓名
            student_id (str): 11位学号

        Returns:
            str: 19位的取件码
        """
        
        #将传入的两个字符串合并,用于生成哈希值
        new_string=name+student_id
        pickup_code=int(str(hash(new_string)))
        if pickup_code<0:
            pickup_code=(-1)*pickup_code
        if len(str(pickup_code)) < 19:
            while len(str(pickup_code)) < 19:
                pickup_code=pickup_code*10
            # pickup_code=pickup_code*10
        pickup_code=str(pickup_code)
        return pickup_code
        pass
    
    def zhuandenglu():
        window.destroy()
        denglu.run_sign_in_page()


    def sign_up()->dict:
        """从注册页面的输入框中获取用户名,用户学号,用户电话号码,用户密码

        Returns:
            dict: 返回记录了上述信息的字典
        """
        """
        连接数据库,以便后续对数据库进行操作
        """
        myconn=pymysql.connect(host="localhost",
                            user="root",
                            password="liang1925tt",
                            database="cquptems_db",
                            port=3306,charset="utf8")
        #获取游标对象
        cur = myconn.cursor()
        # global user_name,user_student_ID,user_phone_number,user_password
        user_name=entry_name.get()
        user_student_ID=entry_student_ID.get()
        user_phone_number=entry_phone_number.get()
        user_password=entry_password.get()
        #生成取件码
        #todo:在这里要生成取件码
        pickup_code=generate_unique_pickup_code(str(user_name),str(user_student_ID))       
        print("用户姓名: ",user_name,
              "学号: ",user_student_ID,
              "电话号码: ",user_phone_number,
              "密码: ",user_password,
              "取件码: ",pickup_code)        

        #定义SQL语句
        sql_sentence=f"""
        
        INSERT INTO Users(USER_NAME, USER_STUDENT_ID, USER_PHONE_NUMBER, UNIQUE_PICKUP_CODE, USER_PASSWORD)
        VALUES
        ('{user_name}','{user_student_ID}','{user_phone_number}','{pickup_code}','{user_password}');
        """
        #执行SQL语句,如果执行成功会获得成功执行的行数
        excute_result = cur.execute(sql_sentence)
        #提交SQL执行结果
        myconn.commit()
        #关闭连接
        myconn.close()
        print("用户姓名: ",user_name,
              "学号: ",user_student_ID,
              "电话号码: ",user_phone_number,
              "密码: ",user_password,
              "取件码: ",pickup_code)
        
        print("变量类型",type(user_name),type(user_student_ID),type(user_phone_number),type(user_password))
        #如果注册成功则显示注册成功的信息
        if excute_result:
            mgbox.showinfo(title="注册成功",
                           message="注册成功\n菜鸟小邮欢迎你")
            pass
        else:
            mgbox.showwarning(title="注册失败",
                              message="注册失败!请重试")
            pass
        return {"user_name":user_name,
                "user_student_ID":user_student_ID,
                "user_phone_number":user_phone_number,
                "user_password":user_password}
        ...

    canvas = Canvas(
        window,
        bg = "#7349be",
        height = 634,
        width = 1024,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("purple_cloud_2_resize.png"))
    image_1 = canvas.create_image(
        256.0,
        317.0,
        image=image_image_1
    )

    canvas.create_text(
        679.0,
        18.0,
        anchor="nw",
        text="菜鸟小邮--错取快递管理系统",
        fill="#000000",
        font=("Inter", 15 * -1)
    )

    canvas.create_text(
        696.0,
        68.0,
        anchor="nw",
        text="欢迎注册",
        fill="#000000",
        font=("Inter", 40 * -1)
    )

    canvas.create_text(
        563.0,
        161.0,
        anchor="nw",
        text="姓名",
        fill="#000000",
        font=("Inter Regular", 24 * -1)
    )

    entry_name_image = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        781.5,
        171.0,
        image=entry_name_image
    )
    entry_name = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        #textvariable=user_name
    )
    entry_name.place(
        x=662.0,
        y=148.0,
        width=239.0,
        height=44.0
    )

    canvas.create_text(
        563.0,
        239.0,
        anchor="nw",
        text="学号",
        fill="#000000",
        font=("Inter Regular", 24 * -1)
    )

    entry_student_ID_image = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        781.5,
        249.0,
        image=entry_student_ID_image
    )
    entry_student_ID = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        #textvariable=user_student_ID
    )
    entry_student_ID.place(
        x=662.0,
        y=226.0,
        width=239.0,
        height=44.0
    )

    canvas.create_text(
        563.0,
        317.0,
        anchor="nw",
        text="电话",
        fill="#000000",
        font=("Inter Regular", 24 * -1)
    )

    entry_phone_number_image = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        781.5,
        327.0,
        image=entry_phone_number_image
    )
    entry_phone_number = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        #textvariable=user_phone_number
    )
    entry_phone_number.place(
        x=662.0,
        y=304.0,
        width=239.0,
        height=44.0
    )

    canvas.create_text(
        563.0,
        395.0,
        anchor="nw",
        text="密码",
        fill="#000000",
        font=("Inter Regular", 24 * -1)
    )

    entry_password_image = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        781.5,
        405.0,
        image=entry_password_image
    )
    entry_password = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        show='*',
        #textvariable=user_password
    )
    entry_password.place(
        x=662.0,
        y=382.0,
        width=239.0,
        height=44.0
    )

    # button_image_1 = PhotoImage(
    #     file=relative_to_assets("button_1.png"))
    sign_up_button = Button(
        #image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        #command=lambda: print("注册"),
        relief="flat",
        text="注册",
        bg="#6b69d6",
        command=sign_up
    )
    sign_up_button.place(
        x=723.0,
        y=554.0,
        width=117.0,
        height=55.0
    )

    canvas.create_text(
        679.0,
        483.0,
        anchor="nw",
        text="已有账号?",
        fill="#FFFFFF",
        font=("Inter Regular", 19 * -1)
    )

    # button_image_2 = PhotoImage(
    #     file=relative_to_assets("button_2.png"))
    sign_in_button = Button(
        #image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=zhuandenglu,
        relief="flat",
        text="登录",
        bg="#54db79"
    )
    sign_in_button.place(
        x=768.0,
        y=477.0,
        width=82.0,
        height=42.0
    )

    print(user_name,user_student_ID,user_phone_number,user_password)
    window.resizable(False, False)
    window.mainloop()
    
    pass

if __name__ == "__main__":
    run_sign_up_page()